export type Language = 'en' | 'ru';

export const languageStorageKey = 'quizroom_language';

export const texts = {
  en: {
    appTitle: 'Class quizzes',
    back: 'Back',
    best: 'Best',
    close: 'Close',
    code: 'Code',
    coins: 'coins',
    correctAnswers: 'Correct answers',
    dailyClaimed: 'Daily bonus claimed',
    dayStreak: 'Fire streak',
    english: 'English',
    explore: 'Explore',
    google: 'Continue with Google',
    guest: 'Continue as guest',
    join: 'Join',
    language: 'Language',
    level: 'Level',
    loading: 'Loading...',
    login: 'Log in',
    logout: 'Sign out',
    newStreak: 'New streak',
    noQuizzes: 'No quizzes found. Try another topic.',
    noTimer: 'No timer',
    profile: 'Profile',
    publish: 'Publish',
    question: 'Question',
    russian: 'Русский',
    saveProfile: 'Save profile',
    search: 'Search quizzes',
    shop: 'Shop',
    signup: 'Sign up',
    or: 'or',
    streakHint: 'Start a 2 day streak',
    streakTitle: 'day streak',
    yourNickname: 'Your nickname',
    welcomeAction: 'Start',
    welcomeTitle: 'Quizzes where you answer, create, and grow your profile',
    welcomeText: 'Play short quizzes, collect coins, and unlock new profile rewards.',
    welcomeOneTitle: 'Play quizzes',
    welcomeOneText: 'Choose a ready quiz or enter a code from a friend.',
    welcomeTwoTitle: 'Create your own',
    welcomeTwoText: 'Build a quiz, share the code, and host a mini competition.',
    welcomeThreeTitle: 'Keep your streak',
    welcomeThreeText: 'Come back every day so the fire stays alive.',
  },
  ru: {
    appTitle: 'Классные викторины',
    back: 'Назад',
    best: 'Лучший',
    close: 'Закрыть',
    code: 'Код',
    coins: 'coins',
    correctAnswers: 'Правильные ответы',
    dailyClaimed: 'Ежедневный бонус получен',
    dayStreak: 'Огонек',
    english: 'English',
    explore: 'Играть',
    google: 'Войти через Google',
    guest: 'Продолжить как гость',
    join: 'Войти',
    language: 'Язык',
    level: 'Уровень',
    loading: 'Загрузка...',
    login: 'Войти',
    logout: 'Выйти',
    newStreak: 'Новый streak',
    noQuizzes: 'Викторины не найдены. Попробуй другую тему.',
    noTimer: 'Без таймера',
    profile: 'Профиль',
    publish: 'Создать',
    question: 'Вопрос',
    russian: 'Русский',
    saveProfile: 'Сохранить профиль',
    search: 'Поиск викторин',
    shop: 'Магазин',
    signup: 'Регистрация',
    or: 'или',
    streakHint: 'Начни streak на 2 дня',
    streakTitle: 'дней подряд',
    yourNickname: 'Твой ник',
    welcomeAction: 'Начать',
    welcomeTitle: 'Викторины, где ты отвечаешь, создаешь и прокачиваешь профиль',
    welcomeText: 'Играй в короткие викторины, собирай coins и открывай новые награды профиля.',
    welcomeOneTitle: 'Играй в викторины',
    welcomeOneText: 'Выбирай готовую викторину или вводи код от друга.',
    welcomeTwoTitle: 'Создавай свои',
    welcomeTwoText: 'Собери викторину, поделись кодом и устрой мини-соревнование.',
    welcomeThreeTitle: 'Держи streak',
    welcomeThreeText: 'Заходи каждый день, чтобы огонек не потух.',
  },
} satisfies Record<Language, Record<string, string>>;

export type Texts = typeof texts.en;
