export type Language = 'en' | 'ru';

export const languageStorageKey = 'quizroom_language';

export const texts = {
  en: {
    appTitle: 'Class quizzes',
    back: 'Back',
    best: 'Best',
    close: 'Close',
    code: 'Code',
    coins: 'coins',
    correctAnswers: 'Correct answers',
    dailyClaimed: 'Daily bonus claimed',
    dayStreak: 'Fire streak',
    english: 'English',
    explore: 'Explore',
    google: 'Continue with Google',
    guest: 'Continue as guest',
    join: 'Join',
    language: 'Language',
    settings: 'Settings',
    appSettings: 'App settings',
    theme: 'Theme',
    themeHint: 'Choose a comfortable look.',
    lightTheme: 'Light',
    warmTheme: 'Warm',
    darkTheme: 'Calm dark',
    music: 'Music',
    musicHint: 'Turn background music on or off.',
    switchLanguageHint: 'Switch interface language.',
    liveGame: 'Live game',
    liveHost: 'Live host',
    endHost: 'End host',
    joinCode: 'Join code',
    copied: 'Copied',
    copyJoinLink: 'Copy join link',
    playersJoined: 'Players joined',
    liveRound: 'Live round',
    waitingRoom: 'Waiting room',
    finalLeaderboard: 'Final leaderboard',
    waitingForPlayers: 'Waiting for players to enter the code.',
    startGame: 'Start game',
    playersAnswered: 'players answered',
    showLeaderboard: 'Show leaderboard',
    nextQuestion: 'Next question',
    waitingForHost: 'Waiting for the host to start',
    playersInRoom: 'players are in the room.',
    chooseAnswer: 'Choose an answer',
    answerSaved: 'Answer saved',
    waitingForEveryone: 'Waiting for everyone',
    results: 'Results',
    roundResults: 'Round results',
    correctAnswer: 'Correct answer',
    correct: 'Correct',
    common: 'Common',
    collapse: 'Collapse',
    legendary: 'Legendary',
    expand: 'Expand',
    wrong: 'Wrong',
    noAnswer: 'No answer',
    leaderboardEmpty: 'Leaderboard will appear after players join.',
    joinedAs: 'You joined as',
    powerUsed: 'Power used',
    skinRemovedWrongAnswer: 'removed one wrong answer for you.',
    removeWrongAnswerAbility: 'Once per quiz, remove one wrong answer.',
    normalModeDescription: 'Normal mode: answer all questions before time runs out.',
    hardcoreModeDescription: 'Hardcore: one mistake ends the run.',
    blitzModeDescription: 'Blitz: only 8 seconds for each question.',
    practiceModeDescription: 'Practice: no timer, learn calmly.',
    finalBossModeDescription: 'Final Boss: 10 seconds and one mistake ends the run.',
    shopTitle: 'Shop',
    skins: 'Skins',
    youHaveCoins: 'You have',
    rare: 'Rare',
    epic: 'Epic',
    legend: 'Legend',
    opening: 'Opening',
    open: 'Open',
    youGot: 'You got',
    duplicateReward: 'Duplicate reward',
    newCharacterAdded: 'New character added to your skins.',
    ability: 'Ability',
    packOnly: 'Pack only',
    free: 'Free',
    equipped: 'Equipped',
    equip: 'Equip',
    buy: 'Buy',
    nicknameBorders: 'Nickname borders',
    nameStyles: 'Name styles',
    newNameFrameAdded: 'New nickname border added to your styles.',
    createQuiz: 'Create quiz',
    quizTitle: 'Quiz title',
    shortDescription: 'Short description',
    answer: 'Answer',
    addQuestion: 'Add question',
    remove: 'Remove',
    saving: 'Saving...',
    shareQuiz: 'Share quiz',
    aiHelper: 'AI helper',
    generateQuizDraft: 'Generate quiz draft',
    topicPlaceholder: 'Topic, for example: Kazakhstan history',
    questions: 'questions',
    generating: 'Generating...',
    generateWithAi: 'Generate with AI',
    couldNotGenerateQuiz: 'Could not generate quiz.',
    mistakes: 'Mistakes',
    total: 'Total',
    quizComplete: 'Quiz complete',
    hardcoreMode: 'Hardcore mode',
    hardcoreRunFailed: 'Hardcore run failed!',
    perfectScore: 'Perfect score!',
    greatJob: 'Great job!',
    niceProgress: 'Nice progress!',
    keepPracticing: 'Keep practicing!',
    yourAnswer: 'Your answer',
    backToQuizzes: 'Back to quizzes',
    stats: 'Stats',
    average: 'Average',
    levelProgress: 'Level progress',
    levelPlaylist: 'Level playlist',
    eightLevelPlaylist: '8 level playlist',
    xpToLevel: 'XP to level',
    prizePlacesEmpty: 'Prize places will appear after players finish.',
    place: 'place',
    host: 'Host',
    normal: 'Normal',
    hardcore: 'Hardcore',
    blitz: 'Blitz',
    practice: 'Practice',
    finalBoss: 'Final Boss',
    level: 'Level',
    loading: 'Loading...',
    login: 'Log in',
    logout: 'Sign out',
    newStreak: 'New streak',
    noQuizzes: 'No quizzes found. Try another topic.',
    noTimer: 'No timer',
    profile: 'Profile',
    publish: 'Publish',
    question: 'Question',
    russian: 'Русский',
    saveProfile: 'Save profile',
    search: 'Search quizzes',
    shop: 'Shop',
    signup: 'Sign up',
    or: 'or',
    streakHint: 'Start a 2 day streak',
    streakTitle: 'day streak',
    yourNickname: 'Your nickname',
    welcomeAction: 'Start',
    welcomeTitle: 'Quizzes where you answer, create, and grow your profile',
    welcomeText: 'Play short quizzes, collect coins, and unlock new profile rewards.',
    tutorialTitle: 'Mini tutorial',
    tutorialOneTitle: 'Find or join',
    tutorialOneText: 'Open Explore, choose a quiz, or enter a code from a host.',
    tutorialTwoTitle: 'Answer together',
    tutorialTwoText: 'In live games, wait for the host, answer, then wait for everyone.',
    tutorialThreeTitle: 'Level up',
    tutorialThreeText: 'Correct answers give XP, coins, streaks, and profile rewards.',
    welcomeOneTitle: 'Play quizzes',
    welcomeOneText: 'Choose a ready quiz or enter a code from a friend.',
    welcomeTwoTitle: 'Create your own',
    welcomeTwoText: 'Build a quiz, share the code, and host a mini competition.',
    welcomeThreeTitle: 'Keep your streak',
    welcomeThreeText: 'Come back every day so the fire stays alive.',
  },
  ru: {
    appTitle: 'Классные викторины',
    back: 'Назад',
    best: 'Лучший',
    close: 'Закрыть',
    code: 'Код',
    coins: 'coins',
    correctAnswers: 'Правильные ответы',
    dailyClaimed: 'Ежедневный бонус получен',
    dayStreak: 'Огонек',
    english: 'English',
    explore: 'Играть',
    google: 'Войти через Google',
    guest: 'Продолжить как гость',
    join: 'Войти',
    language: 'Язык',
    settings: 'Настройки',
    appSettings: 'Настройки приложения',
    theme: 'Тема',
    themeHint: 'Выбери удобный внешний вид.',
    lightTheme: 'Светлая',
    warmTheme: 'Тёплая',
    darkTheme: 'Тёмная спокойная',
    music: 'Музыка',
    musicHint: 'Включи или выключи фоновую музыку.',
    switchLanguageHint: 'Смени язык интерфейса.',
    liveGame: 'Live-игра',
    liveHost: 'Live-хост',
    endHost: 'Закончить хост',
    joinCode: 'Код входа',
    copied: 'Скопировано',
    copyJoinLink: 'Скопировать ссылку',
    playersJoined: 'Игроки зашли',
    liveRound: 'Live-раунд',
    waitingRoom: 'Комната ожидания',
    finalLeaderboard: 'Финальный лидерборд',
    waitingForPlayers: 'Ждём, пока игроки введут код.',
    startGame: 'Начать игру',
    playersAnswered: 'игроков ответили',
    showLeaderboard: 'Показать лидерборд',
    nextQuestion: 'Следующий вопрос',
    waitingForHost: 'Ждём, пока хост начнёт игру',
    playersInRoom: 'игроков в комнате.',
    chooseAnswer: 'Выбери ответ',
    answerSaved: 'Ответ сохранён',
    waitingForEveryone: 'Ждём остальных',
    results: 'Результаты',
    roundResults: 'Результаты раунда',
    correctAnswer: 'Правильный ответ',
    correct: 'Правильно',
    common: 'Обычный',
    collapse: 'Свернуть',
    legendary: 'Легендарный',
    expand: 'Открыть',
    wrong: 'Неправильно',
    noAnswer: 'Нет ответа',
    leaderboardEmpty: 'Лидерборд появится, когда игроки зайдут.',
    joinedAs: 'Ты зашёл как',
    powerUsed: 'Способность использована',
    skinRemovedWrongAnswer: 'убрал один неправильный ответ для тебя.',
    removeWrongAnswerAbility: 'Один раз за квиз убирает один неправильный ответ.',
    normalModeDescription: 'Обычный режим: ответь на все вопросы до конца времени.',
    hardcoreModeDescription: 'Hardcore: одна ошибка завершает попытку.',
    blitzModeDescription: 'Blitz: только 8 секунд на каждый вопрос.',
    practiceModeDescription: 'Практика: без таймера, учись спокойно.',
    finalBossModeDescription: 'Final Boss: 10 секунд и одна ошибка завершает попытку.',
    shopTitle: 'Магазин',
    skins: 'Скины',
    youHaveCoins: 'У тебя',
    rare: 'Редкий',
    epic: 'Эпический',
    legend: 'Легенда',
    opening: 'Открываем',
    open: 'Открыть',
    youGot: 'Ты получил',
    duplicateReward: 'Награда за повтор',
    newCharacterAdded: 'Новый персонаж добавлен к твоим скинам.',
    ability: 'Способность',
    packOnly: 'Только из пака',
    free: 'Бесплатно',
    equipped: 'Надето',
    equip: 'Надеть',
    buy: 'Купить',
    nicknameBorders: 'Рамки ника',
    nameStyles: 'Стили имени',
    newNameFrameAdded: 'Новая рамка ника добавлена к стилям.',
    createQuiz: 'Создать викторину',
    quizTitle: 'Название викторины',
    shortDescription: 'Короткое описание',
    answer: 'Ответ',
    addQuestion: 'Добавить вопрос',
    remove: 'Удалить',
    saving: 'Сохраняем...',
    shareQuiz: 'Поделиться викториной',
    aiHelper: 'AI-помощник',
    generateQuizDraft: 'Сгенерировать черновик',
    topicPlaceholder: 'Тема, например: история Казахстана',
    questions: 'вопросов',
    generating: 'Генерируем...',
    generateWithAi: 'Сгенерировать с AI',
    couldNotGenerateQuiz: 'Не получилось сгенерировать викторину.',
    mistakes: 'Ошибки',
    total: 'Всего',
    quizComplete: 'Викторина завершена',
    hardcoreMode: 'Hardcore-режим',
    hardcoreRunFailed: 'Hardcore-попытка провалена!',
    perfectScore: 'Идеальный результат!',
    greatJob: 'Отличная работа!',
    niceProgress: 'Хороший прогресс!',
    keepPracticing: 'Продолжай тренироваться!',
    yourAnswer: 'Твой ответ',
    backToQuizzes: 'Назад к викторинам',
    stats: 'Статистика',
    average: 'Средний результат',
    levelProgress: 'Прогресс уровня',
    levelPlaylist: 'Плейлист уровней',
    eightLevelPlaylist: 'Плейлист из 8 уровней',
    xpToLevel: 'XP до уровня',
    prizePlacesEmpty: 'Призовые места появятся после завершения игроков.',
    place: 'место',
    host: 'Хост',
    normal: 'Обычный',
    hardcore: 'Hardcore',
    blitz: 'Blitz',
    practice: 'Практика',
    finalBoss: 'Final Boss',
    level: 'Уровень',
    loading: 'Загрузка...',
    login: 'Войти',
    logout: 'Выйти',
    newStreak: 'Новый streak',
    noQuizzes: 'Викторины не найдены. Попробуй другую тему.',
    noTimer: 'Без таймера',
    profile: 'Профиль',
    publish: 'Создать',
    question: 'Вопрос',
    russian: 'Русский',
    saveProfile: 'Сохранить профиль',
    search: 'Поиск викторин',
    shop: 'Магазин',
    signup: 'Регистрация',
    or: 'или',
    streakHint: 'Начни streak на 2 дня',
    streakTitle: 'дней подряд',
    yourNickname: 'Твой ник',
    welcomeAction: 'Начать',
    welcomeTitle: 'Викторины, где ты отвечаешь, создаешь и прокачиваешь профиль',
    welcomeText: 'Играй в короткие викторины, собирай coins и открывай новые награды профиля.',
    tutorialTitle: 'Мини-туториал',
    tutorialOneTitle: 'Найди или войди',
    tutorialOneText: 'Открой Играть, выбери викторину или введи код от хоста.',
    tutorialTwoTitle: 'Отвечай вместе',
    tutorialTwoText: 'В live-игре жди старт от хоста, отвечай и жди остальных.',
    tutorialThreeTitle: 'Прокачивайся',
    tutorialThreeText: 'Правильные ответы дают XP, coins, streak и награды профиля.',
    welcomeOneTitle: 'Играй в викторины',
    welcomeOneText: 'Выбирай готовую викторину или вводи код от друга.',
    welcomeTwoTitle: 'Создавай свои',
    welcomeTwoText: 'Собери викторину, поделись кодом и устрой мини-соревнование.',
    welcomeThreeTitle: 'Держи streak',
    welcomeThreeText: 'Заходи каждый день, чтобы огонек не потух.',
  },
} satisfies Record<Language, Record<string, string>>;

export type Texts = typeof texts.en;
